internal/logic/area/area.go
internal/logic/sys_audit/sys_audit.go
internal/logic/sys_organization/sys_organization.go
internal/logic/sys_permission/sys_permission.go
internal/logic/sys_role/sys_role.go
internal/logic/sys_user/sys_user.go
utility/daoctl/daoctl.go

pref daoctl

---

go.mod
go.sum
internal/logic/auth/auth.go
internal/logic/sys_user/sys_user.go
utility/en_crypto/pwd_hash.go

- 优化前:  md5加密
- 优化后: Password = 用户id进行MD5后取其后八位(盐) + 用户指定的密码  --> 进行hash，得到最终的密码

pref: 创建用户更换加密算法

---

utility/daoctl/daoctl.go

fix: 排序时加上转驼峰命名方法

---

internal/logic/auth/auth.go
internal/logic/sys_user/sys_user.go

- 如果密码不足8位，直接补0，就使用md5加密id后进行截取了，因为同时有md5和hash算法多少会有性能影响

pref: 优化用户密码的产生

---

api_v1/sysapi/sys_auth.go
controller/sys_auth.go
internal/logic/auth/auth.go

fix: gcache缓存问题修复

---

model/search.go

pref: 修改排序字段的命名规范

---

utility/daoctl/daoctl.go

fix: 修复无法返回总页数，优化daoctl方法

---

api_v1/sysapi/sys_auth.go
controller/sys_auth.go
internal/logic/auth/auth.go
model/auth.go
service/auth.go

- 新增手机号+验证码登录：
- 在此之前，用户除了提供验证码，还需要补全自己的用户名信息  林 * 菲
- 短信验证,如果验证码通过，那就不需要判断密码啥的，直接返回用户信息即可

feat: 新增手机号+验证码登录

---

api_v1/sysapi/sys_auth.go
controller/sys_auth.go
internal/logic/auth/auth.go
internal/service/auth.go
model/auth.go
service/auth.go

参数调整：
- 忘记密码：
- 用户名
- 验证码
- 手机号码
- 重置密码：
- 当前密码 / 密钥
- 新密码
- 确认新密码

Pref reset password

---

internal/logic/file/file.go
model/dao/internal/sys_file.go
model/dao/internal/sys_user.go
model/do/sys_file.go
model/do/sys_user.go
model/entity/sys_file.go
model/entity/sys_user.go

Pref model

---

model/dao/internal/fd_account_bill.go
model/do/fd_account_bill.go
model/entity/fd_account_bill.go
model/fd_account_bill.go

交易类型，1转账、2消费、4退款、8佣金、16保证金、32诚意金、64手续费/服务费、128提现、256充值、512营收，8192其它

pref: 统一交易类型命名

---

model/enum/audit/action_type.go
model/enum/audit/event.go
model/enum/auth/action_type.go
model/enum/financial/inout_type.go
model/enum/financial/trade_type.go
model/enum/upload/event_state.go
model/enum/user/event.go
model/enum/user/state.go
model/enum/user/type.go

fix: 枚举类型取值空指针问题修复

---

internal/logic/fd_invoice/fd_invoice.go
internal/logic/fd_invoice_detail/fd_invoice_detail.go
model/enum/invoice/audit_type.go
model/enum/invoice/state.go
model/enum/invoice/type.go
model/fd_invoice_detail.go
service/fd_invoice.go
service/fd_invoice_detail.go

pref 完善财务相关业务功能

---

api_v1/sys_api/sys_user.go
component.go
go.mod
go.sum
internal/cmd/cmd.go
internal/logic/sys_auth/sys_auth.go
internal/logic/sys_user/sys_user.go
sys_controller/sys_user.go
sys_service/sys_user.go

规则：
- 超级管理员无需验证验证，
- XX商管理员重置员工密码无需验证

feat: 添加重置用户密码接口

---

database/latest.sql
database/migrations/000007_v01.1216.up.sql
internal/logic/sys_permission/sys_permission.go
sys_model/sys_dao/internal/sys_permission.go
sys_model/sys_do/sys_permission.go
sys_model/sys_entity/sys_permission.go

pref: 优化权限树的返回

---

go.sum
internal/cmd/cmd.go
internal/logic/sys_bizctx/sys_bizctx.go
internal/logic/sys_casbin/sys_casbin.go
internal/logic/sys_permission/sys_permission.go
manifest/config/config.yaml
sys_service/sys_casbin.go
sys_service/sys_permission.go

1.首先在入口处注册Casbin中间件，
2.在中间件里面进行权限判断
3.权限判断的具体方法，我使用的是它框架自带的Enforce()
4.参数解析:
Enforce(用户id,域，资源id, 方法)
5.返回值true有权限，反之

feat: Casbin实现接口访问的权限控制

---

internal/logic/sys_casbin/sys_casbin.go
internal/logic/sys_permission/sys_permission.go
sys_model/sys_casbin.go
sys_model/sys_enum/internal/casbin/event.go
sys_model/sys_enum/internal/casbin/index.go
sys_model/sys_enum/sys_enum.go
sys_service/sys_casbin.go
sys_service/sys_permission.go

- 修改GetPermissionByUrl方法的返回值 
- id -->  *sys_entity.SysPermission
- Casbin的EnforceCheck检验权限参数修改：
-  域修改为项目中的常量
- Casbin定义Hook
- 具体业务使用还未实现....

Pref: 优化Casbin权限相关方法

---

database/migrations/000008_v01.1217.up.sql
internal/logic/sys_role/sys_role.go
sys_model/sys_dao/internal/sys_role.go
sys_model/sys_do/sys_role.go
sys_model/sys_entity/sys_role.go
sys_model/sys_role.go

- 数据表sys_role添加字段：
-  union_main_id  '主体id
- is_sys  '是否允许删除和修改: 0允许  1禁止,并拥有默认权限
- 判断角色是否存在的时候增加UnionMainId条件限定
- 因为不同的商下面可能都有Boos、管理员,

pref: 完善角色模块

---

api_v1/sys_api/sys_file.go
internal/logic/sys_file/sys_file.go
sys_controller/sys_file.go
sys_service/sys_file.go

feat: 增加根据id获取图片并显示接口

---

internal/logic/sys_area/sys_area.go
sys_controller/sys_config.go
sys_controller/sys_organization.go
sys_controller/sys_role.go
sys_model/sys_search.go
utility/daoctl/daoctl.go

- 字段类型：int64
- 字段结构体: PaginationRes

Feat: 列表查询的时候返回Total总数字段

---

sys_model/sdk_baidu.go

- bank_name -> bankName
- 下划线分隔命名换成驼峰命名法

pref:银行卡识别返回结果字段风格统一

---

api_v1/sys_api/sys_file.go
internal/logic/sys_file/sys_file.go
sys_controller/sys_file.go
sys_service/sys_file.go

- GetFile --> GetFileById
- Request参数去除

pref: 文件获取重命名并移除多余参数

---

database/migrations/000009_v05.1226.up.sql
internal/logic/sys_role/sys_role.go
sys_model/sys_dao/internal/sys_role.go
sys_model/sys_do/sys_role.go
sys_model/sys_entity/sys_role.go
sys_model/sys_role.go

fix: 去掉sys_role数据模型冗余字段

---

internal/logic/sys_role/sys_role.go
sys_model/sys_role.go
sys_service/sys_role.go

- 修改前：能获取所有的角色列表
- 修改后：获取系统角色列表 + 自己商角色列表

feat: 优化获取角色列表

---

api_v1/sys_api/sys_file.go
internal/logic/sys_file/sys_file.go
sys_controller/sys_file.go
sys_service/sys_file.go

GetFileById 这个接口是显示图片的接口：
- 参数2个：图片id + v类型标识(0临时文件 1永久文件)
- 通过v判断去数据库查找还是缓存查找
- getFileFromSql  从数据库查找文件
- getFileFromCache 从缓存查找文件
- 最后根据file的路径显示图片

pref: 优化获取文件功能

---

internal/logic/sys_file/sys_file.go

- 修复文件上传需要保存，修改为不需要保存
- 增加显示缓存图片的功能，包括接口  /showFile

fix: 文件相关操作修复

---

internal/logic/sys_file/sys_file.go
internal/logic/sys_jwt/sys_jwt.go
internal/logic/sys_role/sys_role.go
sys_controller/sys_role.go
sys_model/jwt.go
sys_service/sys_jwt.go
sys_service/sys_role.go

- SetRoleUser 设置角色用户的时候判断是否跨商操作
- 优化CreateRoleInfo控制层方法命名

feat: 设置角色用户的时候判断是否跨商操作

---

database/migrations/000010_v06.1229.up.sql
sys_model/sys_dao/internal/sys_permission.go
sys_model/sys_do/sys_permission.go
sys_model/sys_entity/sys_permission.go

feat: permission数据表添加排序字段sort

---

internal/logic/sys_auth/sys_auth.go
sys_model/sys_user.go

fix: 修复用户注册验证码及逻辑优化

---

internal/logic/sys_role/sys_role.go
internal/logic/sys_user/sys_user.go
utility/daoctl/daoctl.go

- 部分功能，使用缓存进行优化
- sql优化，避免大量重复查询

pref: 获取列表使用缓存优化

---

internal/boot/boot.go
internal/logic/sys_file/sys_file.go
sys_consts/global.go
sys_service/sys_file.go

feat: 增加获取请求文件url方法

---

internal/logic/sys_jwt/sys_jwt.go
sys_model/jwt.go

pref: 优化JwtCustomClaims对象的使用

---

internal/logic/sys_permission/sys_permission.go

- QueryPermissionList方法
- sort排序字段

feat: 查询权限列表逻辑增加排序sort判断

---

internal/logic/sys_role/sys_role.go
sys_model/jwt.go
sys_model/sys_role.go
utility/daoctl/daoctl.go

fix: 修复daoctl大小写转换方法
- CaseCamelLower  --> ToLower
fix: 将项目中忽略输入输出替换成json:"-"
- 修改前：p:"-"
- 修改后：json:"-"

fix: 修复公共daoctl

---

utility/deepcopy/deepcopy.go
utility/empty/empty.go
utility/json/json.go
utility/kmap/kmap.go
utility/reflection/reflection.go
utility/rwmutex/rwmutex.go

feat 添加深度拷贝实用包
feat 添加json实用包
feat 添加反射实用包
feat 添加互斥锁实用包

feat 添加 kmap 实用包

---

api_v1/sys_api/sys_permission.go
internal/logic/sys_middleware/sys_middleware.go
internal/logic/sys_permission/sys_permission.go
internal/logic/sys_role/sys_role.go
internal/logic/sys_user/sys_user.go
sys_controller/sys_permission.go
sys_service/sys_middleware.go
sys_service/sys_permission.go
sys_service/sys_user.go

perf 优化权限逻辑实现，改用标识符作为权限校验
pref 简化权限应用

Pref 优化权限逻辑实现，改用标识符作为权限校验，简化权限应用

---

internal/logic/sdk_aliyun/sdk_aliyun.go
internal/logic/sdk_baidu/sdk_baidu.go
internal/logic/sdk_ctyun/sdk_ctyun.go
internal/logic/sdk_huawei/sdk_huawei.go
internal/logic/sdk_tencent/sdk_tencent.go
internal/logic/sys_area/sys_area.go
internal/logic/sys_auth/sys_auth.go
internal/logic/sys_menu/sys_menu.go
internal/logic/sys_organization/sys_organization.go
internal/logic/sys_role/sys_role.go
internal/logic/sys_user/sys_user.go

pref: 优化项目缓存方案

---

internal/logic/sys_file/sys_file.go

- info应该替换成data
- Update应该有Where条件

fix: 修复文件保存方法Bug

---

internal/logic/sys_sms/sys_sms.go
internal/logic/sys_user/sys_user.go
sys_service/sys_sms.go
sys_service/sys_user.go

pref 添加短信校验方法

---

api_v1/sys_api/sys_my.go
internal/logic/sys_user/sys_user.go
sys_controller/sys_my.go
sys_service/sys_user.go

- 接口url：/setUserMobile
- 接口位置：我的
- 接口名称：设置用户手机号
- 注意：默认是修改当前登录用户的手机号

feat: 添加设置用户登录手机号接口

---

utility/daoctl/cache.go

- if判断结果：sys_user || SelectCache:sys_user || SelectCache:default@#sys_user

pref: 优化daoctl删除缓存方法逻辑

---

manifest/config/config.yaml
sys_controller/captcha.go
utility/sys_rules/check_rule.go

- 更新配置文件说明，明确 onSendCaptcha 设置的作用
- 重构验证码发送逻辑，使用新的检查规则函数
- 新增 CheckEnableSendCaptchaRule 函数，用于判断是否允许发送验证码

feat(sys): 优化验证码发送逻辑

---

internal/logic/sys_menu/sys_menu.go
sys_controller/sys_my.go
sys_model/sys_menu.go
sys_service/sys_menu.go

- 合并 SysMenu 和 UpdateSysMenu 结构体
- 添加新字段：SortName, I18NKey, Layout, Hidden
- 移除了未使用的 sys_entity.SysMenu 引用
- 优化了 MyPermission 和 MyMenu 函数的错误处理
- 更新了 SysMenuService 接口，增加了 GetAllMenus 和修改了 GetMenuTree 方法

pref(sys-menu): 重构菜单相逻辑实现

---

example/i18n/en-US.ini
example/i18n/zh-CN.ini

- 将等号两边的空格统一为一个
- 添加缺失的引号
- 删除多余的引号
- 统一日期和时间相关的翻译
请描述此 Pull Request 包含的更改和解决的问题。
请使用关键词链接到此 PR 解决的 Issue：
- Fixes #（issue 编号）
- Resolves #（issue 编号）
- Closes #（issue 编号）
请选择适用的更改类型（在方括号中添加 x）：
请描述您执行的测试：
测试覆盖率百分比（如果适用）：
```
// 如果可能，添加覆盖率报告
```
添加任何关于该 PR 的额外信息。

refactor(i18n): 优化国际化文件格式

---

internal/logic/sys_file/sys_file.go

- 在 SaveFile 方法中添加了对 storageAddr 和 info.Src 相等的检查，避免不必要的文件保存操作。
- 处理了数据库查询错误，确保在保存文件时能够正确记录错误信息。
- 更新了文件保存后的 Hook 调用，确保传递正确的文件信息结构体。
请描述此 Pull Request 包含的更改和解决的问题。
请使用关键词链接到此 PR 解决的 Issue：
- Fixes #（issue 编号）
- Resolves #（issue 编号）
- Closes #（issue 编号）
请选择适用的更改类型（在方括号中添加 x）：
请描述您执行的测试：
测试覆盖率百分比（如果适用）：
```
// 如果可能，添加覆盖率报告
```
添加任何关于该 PR 的额外信息。

fix(sys_file): 修复 SaveFile 方法中的逻辑错误

---

sys_model/sys_dao/internal/sys_category.go
sys_model/sys_do/sys_category.go
sys_model/sys_entity/sys_category.go

- 在 SysCategory 结构体中添加了 Description 字段，用于存储分类的描述信息。
- 更新了相关的 DAO 和数据库实体文件以支持新字段。
请描述此 Pull Request 包含的更改和解决的问题。
请使用关键词链接到此 PR 解决的 Issue：
- Fixes #（issue 编号）
- Resolves #（issue 编号）
- Closes #（issue 编号）
请选择适用的更改类型（在方括号中添加 x）：
请描述您执行的测试：
测试覆盖率百分比（如果适用）：
```
// 如果可能，添加覆盖率报告
```
添加任何关于该 PR 的额外信息。

feat(sys_category): 添加描述字段到系统分类模型
